# fly.toml file generated for kom-spot on 2022-11-16T16:05:16-05:00

app = "kom-spot"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[env]
  DB_HOST = "kom-pg.internal"
  DB_NAME = "spot"
  DB_PORT = "5432"
  DB_USER = "spot"
  HOST = "0.0.0.0"
  LOG_FORMAT = "json"
  PORT = "3000"
  REAL_DOMAIN = "spotie.app"
  REAL_HOSTNAME = "https://spotie.app"
  SQLX_OFFLINE = "true"

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[[services]]
  internal_port = 3000
  processes = ["app"]
  protocol = "tcp"
  script_checks = []
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.http_checks]]
    grace_period = "5s"
    interval = "60s"
    method = "get"
    path = "/status"
    protocol = "http"
    restart_limit = 0
    timeout = "2s"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443
