# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: install rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          components: rustfmt, clippy

      - name: lint
        run: cd server && cargo fmt -- --check && cargo clippy
        
      - name: deploy
        uses: akhileshns/heroku-deploy@v3.12.12
        if: contains(github.ref, 'master')
        with:
          heroku_api_key: ${{ secret.HEROKU_API_KEY }}
          heroku_app_name: "soundlog"
          heroku_email: "james@kominick.com"
          usedocker: true


